version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - api
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    container_name: api
    env_file:
      - ./env/backend.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: "mongo"
    container_name: "mongo-db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iotsnacks
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - iotmongo-db:/data/db
  redis:
    image: redis
volumes:
  iotmongo-db:
